name: Terraform Apply

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  TF_VAR_allowed_address_ssh: "${{ secrets.TF_VAR_ALLOWED_ADDRESS_SSH }}"

jobs:
  terraform-apply:
    name: Terraform Apply
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ~1.4

    - name: Terraform Init
      id: init
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ secrets.TFSTATE_RG }}" \
          -backend-config="storage_account_name=${{ secrets.TFSTATE_SA }}" \
          -backend-config="container_name=${{ secrets.TFSTATE_CONTAINER }}"
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Apply
      run: terraform apply -auto-approve